openapi: 3.0.3
info:
  title: My Clinic Medic
  description: My Clinic Medic APIs
  version: 1.0.0
security:
  - BearerAuth: []
paths:
  /api/v1/my-clinic-medic/hello:
    get:
      summary: Receive Hello Medic
      description: This API provides hello message for medic user
      operationId: hello
      tags:
        - my-clinic-medic
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                type: string
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/my-clinic-medic/cancelTicket/{ticketId}:
    post:
      summary: API to cancel a ticket
      description: This API receives as parameter the ticket id and cancels it
      operationId: cancelTicket
      tags:
        - my-clinic-medic
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: ticketId
          schema:
            type: number
          required: true
          description: The ticket id
      responses:
        200:
          description: ok
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/my-clinic-medic/finishTicket/{ticketId}:
    post:
      summary: API to finish a ticket
      description: This API receives as parameter the ticket id and finishes it
      operationId: finishTicket
      tags:
        - my-clinic-medic
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: ticketId
          schema:
            type: number
          required: true
          description: The ticket id
      responses:
        200:
          description: ok
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/my-clinic-medic/getTicketById/{ticketId}:
    get:
      summary: get a ticket by id
      description: This API is called to get a ticket by its id
      operationId: getTicketById
      tags:
        - my-clinic-medic
      security:
        - bearerAuth: [ ]
      parameters:
        - in: path
          name: ticketId
          schema:
            type: number
          required: true
          description: The ticket id
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TicketInfo'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/my-clinic-medic/getMyTickets:
    get:
      summary: get a ticket by id
      description: This API is called to get all medic tickets
      operationId: getTickets
      tags:
        - my-clinic-medic
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tickets'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/my-clinic-medic/getMyCurrentTickets:
    get:
      summary: get a ticket by id
      description: This API is called to get current medic tickets
      operationId: getCurrentTickets
      tags:
        - my-clinic-medic
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tickets'
        400:
          $ref: '#/components/responses/ClientError'
        500:
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    TicketInfo:
      type: object
      properties:
        id:
          type: number
        productId:
          type: number
        creationDate:
          type: string
        period:
          type: string
        paymentId:
          type: number
        ticketStatus:
          type: string
        doctorId:
          type: number

    Tickets:
      type: array
      items:
        $ref: '#/components/schemas/TicketInfo'

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          description: error code
          example: TECHNICAL_ERROR
        message:
          type: string
          description: Free-form text message describing the error condition
          example: Input parameters validation failed

  responses:
    ClientError:
      description: bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ServerError:
      description: internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'